spring.datasource.url=jdbc:mysql://85.98.94.161:27060/aktour_db?serverTimezone=UTC
spring.datasource.username=ius2026
spring.datasource.password=aktour2026
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
server.port=8080
springdoc.swagger-ui.path=/swagger
springdoc.api-docs.path=/api-docs
server.error.include-binding-errors=always
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.org.hibernate.SQL=DEBUG

admin1.username=admin
admin1.password=admin123
admin1.email=admin@aktourbosna.com

admin2.username=admin2
admin2.password=admin456
admin2.email=admin2@aktourbosna.com

jwt.secret=YWt0b3VyLW1hbmFnZW1lbnQtand0LXNlY3JldC1rZXktMjAyNi12ZXJ5LXNlY3VyZS1sb25nLWVub3VnaC1mb3ItaHMyNTY=
jwt.expiration=86400000
